name 'oraclexe'
maintainer 'awim/mtaqwim'
maintainer_email 'muhammadtaqwiem@gmail.com'
license 'all_rights'
description 'Installs/Configures oraclexe_wrapper'
long_description 'Installs/Configures oraclexe_xe'
version '0.1.0'
